[build-system]
requires = [
    "setuptools >= 58.0.1"
]
build-backend = "setuptools.build_meta"

[project]
name = "pyalfe"
version = "0.0.1"
authors = [
    {name = "Reza Eghbali", email="eghbali68@gmail.com"},
    {email = "reza.eghbali@ucsf.edu"}
]
dependencies = [
    "numpy",
    "Click",
    "dependency_injector",
    "torch",
    "pandas",
    "nibabel",
    "nnunet",
    "nilearn",
]

[project.optional-dependencies]
ants = ["antspyx"]
radiomics = ["Pyradiomics"]

[project.scripts]
pyalfe = "pyalfe.main:main"